<h2> ANOVA</h2>

<b> By Michael KUMAKECH</B>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [13]:
path='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/automobileEDA.csv'
df = pd.read_csv(path)
df.head()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,horsepower-binned,diesel,gas
0,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,13495.0,11.190476,Medium,0,1
1,3,122,alfa-romero,std,two,convertible,rwd,front,88.6,0.811148,...,9.0,111.0,5000.0,21,27,16500.0,11.190476,Medium,0,1
2,1,122,alfa-romero,std,two,hatchback,rwd,front,94.5,0.822681,...,9.0,154.0,5000.0,19,26,16500.0,12.368421,Medium,0,1
3,2,164,audi,std,four,sedan,fwd,front,99.8,0.848630,...,10.0,102.0,5500.0,24,30,13950.0,9.791667,Medium,0,1
4,2,164,audi,std,four,sedan,4wd,front,99.4,0.848630,...,8.0,115.0,5500.0,18,22,17450.0,13.055556,Medium,0,1

In [14]:
df.corr()

,symboling,normalized-losses,wheel-base,length,width,height,curb-weight,engine-size,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,city-L/100km,diesel,gas
symboling,1.000000,0.466264,-0.535987,-0.365404,-0.242423,-0.550160,-0.233118,-0.110581,-0.140019,-0.008245,-0.182196,0.075819,0.279740,-0.035527,0.036233,-0.082391,0.066171,-0.196735,0.196735
normalized-losses,0.466264,1.000000,-0.056661,0.019424,0.086802,-0.373737,0.099404,0.112360,-0.029862,0.055563,-0.114713,0.217299,0.239543,-0.225016,-0.181877,0.133999,0.238567,-0.101546,0.101546
wheel-base,-0.535987,-0.056661,1.000000,0.876024,0.814507,0.590742,0.782097,0.572027,0.493244,0.158502,0.250313,0.371147,-0.360305,-0.470606,-0.543304,0.584642,0.476153,0.307237,-0.307237
length,-0.365404,0.019424,0.876024,1.000000,0.857170,0.492063,0.880665,0.685025,0.608971,0.124139,0.159733,0.579821,-0.285970,-0.665192,-0.698142,0.690628,0.657373,0.211187,-0.211187
width,-0.242423,0.086802,0.814507,0.857170,1.000000,0.306002,0.866201,0.729436,0.544885,0.188829,0.189867,0.615077,-0.245800,-0.633531,-0.680635,0.751265,0.673363,0.244356,-0.244356
height,-0.550160,-0.373737,0.590742,0.492063,0.306002,1.000000,0.307581,0.074694,0.180449,-0.062704,0.259737,-0.087027,-0.309974,-0.049800,-0.104812,0.135486,0.003811,0.281578,-0.281578
curb-weight,-0.233118,0.099404,0.782097,0.880665,0.866201,0.307581,1.000000,0.849072,0.644060,0.167562,0.156433,0.757976,-0.279361,-0.749543,-0.794889,0.834415,0.785353,0.221046,-0.221046
engine-size,-0.110581,0.112360,0.572027,0.685025,0.729436,0.074694,0.849072,1.000000,0.572609,0.209523,0.028889,0.822676,-0.256733,-0.650546,-0.679571,0.872335,0.745059,0.070779,-0.070779
bore,-0.140019,-0.029862,0.493244,0.608971,0.544885,0.180449,0.644060,0.572609,1.000000,-0.055390,0.001263,0.566936,-0.267392,-0.582027,-0.591309,0.543155,0.554610,0.054458,-0.054458
stroke,-0.008245,0.055563,0.158502,0.124139,0.188829,-0.062704,0.167562,0.209523,-0.055390,1.000000,0.187923,0.098462,-0.065713,-0.034696,-0.035201,0.082310,0.037300,0.241303,-0.241303
compression-ratio,-0.182196,-0.114713,0.250313,0.159733,0.189867,0.259737,0.156433,0.028889,0.001263,0.187923,1.000000,-0.214514,-0.435780,0.331425,0.268465,0.071107,-0.299372,0.985231,-0.985231
horsepower,0.075819,0.217299,0.371147,0.579821,0.615077,-0.087027,0.757976,0.822676,0.566936,0.098462,-0.214514,1.000000,0.107885,-0.822214,-0.804575,0.809575,0.889488,-0.169053,0.169053
peak-rpm,0.279740,0.239543,-0.360305,-0.285970,-0.245800,-0.309974,-0.279361,-0.256733,-0.267392,-0.065713,-0.435780,0.107885,1.000000,-0.115413,-0.058598,-0.101616,0.115830,-0.475812,0.475812
city-mpg,-0.035527,-0.225016,-0.470606,-0.665192,-0.633531,-0.049800,-0.749543,-0.650546,-0.582027,-0.034696,0.331425,-0.822214,-0.115413,1.000000,0.972044,-0.686571,-0.949713,0.265676,-0.265676
highway-mpg,0.036233,-0.181877,-0.543304,-0.698142,-0.680635,-0.104812,-0.794889,-0.679571,-0.591309,-0.035201,0.268465,-0.804575,-0.058598,0.972044,1.000000,-0.704692,-0.930028,0.198690,-0.198690
price,-0.082391,0.133999,0.584642,0.690628,0.751265,0.135486,0.834415,0.872335,0.543155,0.082310,0.071107,0.809575,-0.101616,-0.686571,-0.704692,1.000000,0.789898,0.110326,-0.110326
city-L/100km,0.066171,0.238567,0.476153,0.657373,0.673363,0.003811,0.785353,0.745059,0.554610,0.037300,-0.299372,0.889488,0.115830,-0.949713,-0.930028,0.789898,1.000000,-0.241282,0.241282
diesel,-0.196735,-0.101546,0.307237,0.211187,0.244356,0.281578,0.221046,0.070779,0.054458,0.241303,0.985231,-0.169053,-0.475812,0.265676,0.198690,0.110326,-0.241282,1.000000,-1.000000
gas,0.196735,0.101546,-0.307237,-0.211187,-0.244356,-0.281578,-0.221046,-0.070779,-0.054458,-0.241303,-0.985231,0.169053,0.475812,-0.265676,-0.198690,-0.110326,0.241282,-1.000000,1.000000

In [15]:
df.dtypes

symboling              int64
normalized-losses      int64
make                  object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                 float64
stroke               float64
compression-ratio    float64
horsepower           float64
peak-rpm             float64
city-mpg               int64
highway-mpg            int64
price                float64
city-L/100km         float64
horsepower-binned     object
diesel                 int64
gas                    int64
dtype: object

In [16]:
# grouping results
df_gptest = df[['drive-wheels','body-style','price']]
df_gptest.head()

  drive-wheels   body-style    price
0          rwd  convertible  13495.0
1          rwd  convertible  16500.0
2          rwd    hatchback  16500.0
3          fwd        sedan  13950.0
4          4wd        sedan  17450.0

In [17]:
grouped_test2=df_gptest[['drive-wheels', 'price']].groupby(['drive-wheels'])
grouped_test2.head(2)

    drive-wheels    price
0            rwd  13495.0
1            rwd  16500.0
3            fwd  13950.0
4            4wd  17450.0
5            fwd  15250.0
136          4wd   7603.0

In [8]:
df_gptest

    drive-wheels   body-style    price
0            rwd  convertible  13495.0
1            rwd  convertible  16500.0
2            rwd    hatchback  16500.0
3            fwd        sedan  13950.0
4            4wd        sedan  17450.0
..           ...          ...      ...
196          rwd        sedan  16845.0
197          rwd        sedan  19045.0
198          rwd        sedan  21485.0
199          rwd        sedan  22470.0
200          rwd        sedan  22625.0

[201 rows x 3 columns]

<b> We can obtain the values of the method group using the method "get_group".</b>

In [18]:
grouped_test2.get_group('4wd')['price']

4      17450.0
136     7603.0
140     9233.0
141    11259.0
144     8013.0
145    11694.0
150     7898.0
151     8778.0
Name: price, dtype: float64

<b> we can use the function 'f_oneway' in the module 'stats' to obtain the F-test score and P-value.</b>

In [19]:
from scipy import stats

In [20]:
# ANOVA
f_val, p_val = stats.f_oneway(grouped_test2.get_group('fwd')['price'], grouped_test2.get_group('rwd')['price'], grouped_test2.get_group('4wd')['price'])  
 
print( "ANOVA results: F=", f_val, ", P =", p_val)

ANOVA results: F= 67.95406500780399 , P = 3.3945443577151245e-23

<b> Separately: fwd and rwd to see the relationship with price</b>

<b> 4wd and rwd to determine their relationship with price</b>

<b> 4wd and fwd to find the reltionship with price</b>